/*

 FIRSTTILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : C:\Users\jgrot\OneDrive\Desktop\My Game-Boy Games\ComputerArchFinalCode\Art\tiles.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TimemapWidth 10
#define TimemapHeight 10
#define TimemapBank 0

unsigned char Timemap[] =
{
  0x22,0x22,0x22,0x22,0x22,0x10,0x00,0x00,0x00,
  0x03,0x10,0x00,0x00,0x00,0x03,0x10,0x00,0x00,
  0x00,0x03,0x10,0x00,0x00,0x00,0x03,0x10
};

/* End of FIRSTTILEMAP.C */
